name: Build and Deploy Jekyll Site

on:
  push:
    branches:
      - main  # Adjust this to your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0  # Adjust to the Ruby version you're using
        bundler-cache: true

    - name: Install Dependencies
      run: |
        gem install bundler
        bundle install

    - name: Build the Jekyll Site
      run: bundle exec jekyll build --trace

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site
